(TeX-add-style-hook
 "alibindulager"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "preamble"
    "titles")
   (LaTeX-add-labels
    "intro"
    "kriyayogastart"
    "introtrans"
    "kriyayogaend"
    "siddhayoga"
    "cakra1"
    "cakra1trans"
    "cakra2"
    "virgin1"
    "cakra2trans"
    "cakra3"
    "cakra3trans"
    "cakra4"
    "cakra4trans"
    "women"
    "cakra5"
    "cakra5trans"
    "cakra6"
    "cakra6trans"
    "cakra7"
    "cakra7trans"
    "cakra8"
    "cakra8trans"
    "cakra9"
    "cakra9trans"
    "cakra9end"
    "laksyayoga"
    "urdhvalaksya"
    "laksyayogatrans"
    "urdhvalaksyatrans"
    "adholaksya"
    "adholaksyatrans"
    "rajabody"
    "rajabodytrans"
    "anjacihna"
    "anjacihnatrans"
    "caryayoga"
    "caryayogatrans"
    "hathayoga"
    "hathayogatrans"
    "secondtypehatha"
    "secondhathatrans"
    "jnanayogastart"
    "jnanayogatrans1"
    "jnanayogaend"
    "svabhava1"
    "svabhava2"
    "eightenjoyments"
    "padmini"
    "endsvabhava"
    "bahya"
    "bahyatrans"
    "continuebahya"
    "antaralaksya"
    "divisionofchannels"
    "vitalwinds"
    "madhyalaksya"
    "cakranukrama"
    "ashtanga"
    "ashtangatrans"
    "ashtangareversed"
    "internalexternal"
    "lokatraya"
    "quadrupletofworlds"
    "gapn1n2start"
    "sevenislands"
    "saptasamudra"
    "ninecontinents"
    "ninerivers"
    "starstrans"
    "ascetics"
    "attributesrajabody"
    "avadhuta"
    "satyayoganote"
    "lotusofsupport"
    "heartlotus"))
 :latex)

