(TeX-add-style-hook
 "intro"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "preamble"
    "titles")
   (LaTeX-add-labels
    "logo"
    "fig_folio1"
    "generalremarks"
    "dating"
    "ytb-topics"
    "ytb-audience"
    "ramarama"
    "fig:royalyogi2"
    "fig:royalyogi1"
    "fig:royalyogi3"
    "n1description"
    "titlediscussion"
    "mahatmya"
    "fig:titel-hypothese"
    "svaro"
    "tosi"
    "karni"
    "amanaska"
    "yogasamgraha"
    "hathacandrikax"
    "stemma"
    "fig:synoptic1"
    "fig:paup-tree"
    "fig:nj-tree"
    "fig:tree-minspan"
    "fig:stemma"
    "introtrans"
    "kriyayogastart"
    "siddhayoga"
    "kriyayogaend"
    "mantramantra"
    "cakra1"
    "cakra1trans"
    "cakra2"
    "virgin1"
    "cakra2trans"
    "udiyana"
    "cakra3"
    "cakra3trans"
    "cakra4"
    "cakra4trans"
    "women"
    "cakra5"
    "cakra5trans"
    "cakra6"
    "cakra6trans"
    "cakra7"
    "cakra7trans"
    "cakra8"
    "cakra8trans"
    "cakra9"
    "cakra9trans"
    "cakra9kala"
    "cakra9end"
    "laksyayoga"
    "laksyayogatrans"
    "urdhvalaksya"
    "urdhvalaksyatrans"
    "adholaksya"
    "adholaksyatrans"
    "rajabody"
    "rajabodytrans"
    "anjacihna"
    "anjacihnatrans"
    "caryayoga"
    "caryayogatrans"
    "hathayoga"
    "hathayogatrans"
    "secondtypehatha"
    "secondhathatrans"
    "jnanayogastart"
    "jnanayogatrans1"
    "jnanayogaend"
    "svabhava1"
    "tentattvas"
    "svabhava2"
    "eightenjoyments"
    "padmini"
    "endsvabhava"
    "bahya"
    "bahyatrans"
    "continuebahya"
    "antaralaksya"
    "royalpeople"
    "divisionofchannels"
    "vital winds"
    "madhyalaksya"
    "saubhadraverse"
    "cakranukrama"
    "ashtanga"
    "ashtangatrans"
    "ashtangareversed"
    "sukumara"
    "dhyanaredundance"
    "samadhiabsent"
    "internalexternal"
    "lokatraya"
    "quadrupletofworlds"
    "gapn1n2start"))
 :latex)

