(TeX-add-style-hook
 "intro"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "preamble"
    "titles")
   (LaTeX-add-labels
    "fig_folio1"
    "fig_folio11r"
    "generalremarks"
    "dating"
    "tyb-topics"
    "tyb-audience"
    "ramarama"
    "fig:royalyogi2"
    "fig:royalyogi1"
    "fig:royalyogi3"
    "witnessesdescr"
    "n1description"
    "n2description"
    "vdescription"
    "unconsulted"
    "titlediscussion"
    "mahatmya"
    "fig:titel-hypothese"
    "archetypalcolo"
    "fig:colosynop"
    "svaro"
    "tosi"
    "karni"
    "amanaska"
    "yogasamgraha"
    "hathacandrikax"
    "stemma"
    "fig:synoptic3"
    "fig:vexclude"
    "fig:bindefehlerbeta"
    "fig:n1n2"
    "fig:ju1"
    "fig:dk1"
    "fig:u2andbeta"
    "fig:bl"
    "fig:paup1"
    "fig:paup2"
    "fig:nj1"
    "fig:nj2"
    "fig:nj3"
    "fig:tree-minspan"
    "fig:stemmapic"
    "introtrans"
    "kriyayogastart"
    "siddhayoga"
    "kriyayogaend"
    "mantramantra"
    "cakra1"
    "cakra1trans"
    "cakra2"
    "virgin1"
    "cakra2trans"
    "udiyana"
    "cakra3"
    "cakra3trans"
    "cakra4"
    "cakra4trans"
    "women"
    "cakra5"
    "cakra5trans"
    "cakra6"
    "cakra6trans"
    "cakra7"
    "cakra7trans"
    "cakra8"
    "cakra8trans"
    "cakra9"
    "cakra9trans"
    "cakra9kala"
    "cakra9end"
    "laksyayoga"
    "laksyayogatrans"
    "urdhvalaksya"
    "urdhvalaksyatrans"
    "adholaksya"
    "adholaksyatrans"
    "rajabody"
    "rajabodytrans"
    "anjacihna"
    "anjacihnatrans"
    "caryayoga"
    "caryayogatrans"
    "hathayoga"
    "hathayogatrans"
    "secondtypehatha"
    "secondhathatrans"
    "jnanayogastart"
    "jnanayogatrans1"
    "jnanayogaend"
    "svabhava1"
    "svabhava2"
    "tentattvas"
    "eightenjoyments"
    "padmini"
    "bahya"
    "endsvabhava"
    "bahyatrans"
    "continuebahya"
    "antaralaksya"
    "royalpeople"
    "divisionofchannels"
    "vital_winds"
    "madhyalaksya"
    "saubhadraverse"
    "cakranukrama")
   (LaTeX-add-index-entries
    "Tattvayogabindu@\\textit{Tattvayogabindu}"
    "Ramacandra@Rāmacandra"
    "Rajayoga@\\textit{Rājayoga}"
    "yoga taxonomies!Tattvayogabindu@\\textit{Tattvayogabindu}"
    "Kriyayoga@\\textit{Kriyāyoga}"
    "Jnanayoga@\\textit{Jñānayoga}"
    "Caryayoga@\\textit{Caryāyoga}"
    "Hathayoga@\\textit{Haṭhayoga}"
    "Karmayoga@\\textit{Karmayoga}"
    "Layayoga@\\textit{Layayoga}"
    "Dhyanayoga@\\textit{Dhyānayoga}"
    "Mantrayoga@\\textit{Mantrayoga}"
    "Laksyayoga@\\textit{Lakṣyayoga}"
    "Vasanayoga@\\textit{Vāsanāyoga}"
    "Sivayoga@\\textit{Śivayoga}"
    "Brahmayoga@\\textit{Brahmayoga}"
    "Advaitayoga@\\textit{Advaitayoga}"
    "Siddhayoga@\\textit{Siddhayoga}"
    "yogic physiology"
    "Avadhuta@\\textit{Avadhūta}"
    "guru@\\textit{guru}"
    "cosmogony"
    "yogasastrarahasya@\\textit{yogaśāstrarahasya}"
    "Narayanatirtha@Nārāyaṇatīrtha"
    "Yogasiddhantacandrika@\\textit{Yogasiddhāntacandrikā}"
    "Patanjalayogasastra@\\textit{Pātañjalayogaśāstra}"
    "astanga@\\textit{aṣṭāṅga}"
    "Yogasvarodaya@\\textit{Yogasvarodaya}"
    "Pranatosini@\\textit{Prāṇatoṣinī}"
    "Yogakarnika@\\textit{Yogakarṇikā}"
    "Sabdakalpadruma@\\textit{Śabdakalpadruma}"
    "yoga taxonomies!complex early modern taxonomies"
    "Siddhasiddhantapaddhati@\\textit{Siddhasiddhāntapaddhati}"
    "Sundardas@Sundardās"
    "Sarvangayogapradipika@\\textit{Sarvāṅgayogapradīpikā}"
    "Hathapradipika@\\textit{Haṭhapradīpikā}"
    "ksatriya@\\textit{kṣatriya}"
    "Rajayoga@\\textit{Rājayoga}!courtly context"
    "rajan@\\textit{rājan}"
    "cakravartin@\\textit{cakravartin}"
    "Rajayoga@\\textit{Rājayoga}!yoga for kings"
    "Binduyoga@\\textit{Binduyoga}"
    "rubric!final rubric"
    "manuscript transmission!Tattvayogabindu@\\textit{Tattvayogabindu}"
    "Yogasamgraha@\\textit{Yogasaṃgraha}"
    "Sundaradeva@Sundaradeva"
    "Hathasanketacandrika@\\textit{Haṭhasaṅketacandrikā}"
    "stemmatics"
    "stemmatics!computer-assisted"
    "stemma codicum@\\textit{stemma codicum}"
    "editorial policies"
    "critical edition"
    "annotated translation"
    "hermeneutics of difference"
    "Tattvayogabindu@\\textit{Tattvayogabindu}!dating"
    "Nepal Samvat@Nepal Saṃvat"
    "Vikrama Samvat@Vikrama Saṃvat"
    "textual transmission!lacunae"
    "textual transmission!exemplars"
    "textual transmission!corruptions"
    "scribal errors"
    "collation"
    "quotations!unattributed"
    "adhara@\\textit{ādhāra}"
    "Hathasanketacandrika@\\textit{Haṭhasaṅketacandrikā}!dating"
    "Yogacintamani@\\textit{Yogacintāmaṇi}"
    "terminus ante quem@\\textit{terminus ante quem}!Hathasanketacandrika@\\textit{Haṭhasaṅketacandrikā}"
    "terminus ante quem@\\textit{terminus ante quem}!Tattvayogabindu@\\textit{Tattvayogabindu}"
    "Yogasvarodaya@\\textit{Yogasvarodaya}!dating"
    "Siddhasiddhantapaddhati@\\textit{Siddhasiddhāntapaddhati}!dating"
    "Tattvayogabindu@\\textit{Tattvayogabindu}!contents"
    "textual structure!section markers"
    "Siddhakundaliniyoga@\\textit{Siddha[kuṇḍalinī]yoga}"
    "Astangayoga@\\textit{Aṣṭāṅgayoga}"
    "Satyayoga@\\textit{Satyayoga}"
    "Sahajayoga@\\textit{Sahajayoga}"
    "tattva@\\textit{tattva}"
    "yogic body"
    "cosmogenesis"
    "nadi@\\textit{nāḍī}"
    "vayu@\\textit{vāyu}"
    "brahmanda@\\textit{brahmāṇḍa}"
    "pinda@\\textit{piṇḍa}"
    "loka@\\textit{loka}"
    "lokasvamin@\\textit{lokasvāmin}"
    "dvipa@\\textit{dvīpa}"
    "samudra@\\textit{samudra}"
    "khanda@\\textit{khaṇḍa}"
    "parvata@\\textit{parvata}"
    "naksatra@\\textit{nakṣatra}"
    "kala@\\textit{kalā}"
    "candra@\\textit{candra}"
    "surya@\\textit{sūrya}"
    "agni@\\textit{agni}"
    "Saiva paradigm@Śaiva paradigm"
    "cakra@\\textit{cakra}"
    "laksya@\\textit{lakṣya}"
    "vyoma@\\textit{vyoma}"
    "akasa@\\textit{ākāśa}"
    "hrdayakamala@\\textit{hṛdayakamala}"
    "Saiva exegetes@Śaiva exegetes!Kashmir"
    "cosmogony!pentadic"
    "Birch, Jason"
    "Rajayoga@\\textit{Rājayoga}!reception history"
    "Rajayogabhasya@\\textit{Rājayogabhāṣya}"
    "Divakara@Divākara"
    "Bodhasara@\\textit{Bodhasāra}"
    "Tattvayogabindu@\\textit{Tattvayogabindu}!intended audience"
    "warrior aristocracy"
    "royal court!Tattvayogabindu@\\textit{Tattvayogabindu}"
    "ascetics"
    "courtly context"
    "sarirasthiti@\\textit{śarīrasthiti}"
    "ksatriya@\\textit{kṣatriya}!duties"
    "Mysore Palace!yoga tradition"
    "Krishnamacharya, Tirumalai"
    "Krishnaraja Wodiyar IV"
    "Dattatreyayogasastra@\\textit{Dattātreyayogaśāstra}"
    "Mallinson, James"
    "monastic traditions"
    "monastic institutions"
    "royal patronage"
    "mathadhipati@\\textit{maṭhādhipati}"
    "raja@\\textit{rāja}"
    "Sanderson, Alexis"
    "mathadhipati@\\textit{maṭhādhipati}!Śaiva"
    "matha@\\textit{maṭha}"
    "ascetic affiliations"
    "Tattvayogabindu@\\textit{Tattvayogabindu}!Śaiva roots"
    "ascetics!celibate"
    "ascetic yogins"
    "jogi khanda@\\textit{jogī khaṇḍa}"
    "Padmavat@\\textit{Padmāvat}"
    "Rajayoga@\\textit{Rājayoga}!reinterpretation for kings"
    "Rajayoga@\\textit{Rājayoga}!courtly training"
    "cakra@\\textit{cakra}!ninth cakra"
    "antaralaksya@\\textit{antaralakṣya}"
    "ahimsa@\\textit{ahiṃsā}"
    "yama@\\textit{yama}"
    "niyama@\\textit{niyama}"
    "astau bhogah@\\textit{aṣṭau bhogāḥ}"
    "Manasollasa@\\textit{Mānasollāsa}"
    "Somesvara@Someśvara"
    "upabhoga@\\textit{upabhoga}!twenty royal \\textit{upabhoga}s"
    "mendicants"
    "householders"
    "courtly milieu"
    "patronage!wealthy patrons"
    "royal court"
    "siddha@\\textit{siddha}"
    "Hathayoga@Haṭhayoga"
    "hatha@\\textit{haṭha}"
    "Sahajayoga"
    "Moksopaya@\\textit{Mokṣopāya}"
    "Rama@Rāma"
    "Vasistha@Vāsiṣṭha"
    "jnanavatara@\\textit{jñānāvatāra}"
    "Hanneder, Jürgen"
    "krtayuga@\\textit{kṛtayuga}"
    "kriyakrama@\\textit{kriyākrama}"
    "dharma@\\textit{dharma}"
    "kama@\\textit{kāma}"
    "artha@\\textit{artha}"
    "jnanadrsti@\\textit{jñānadṛṣṭi}"
    "adhyatmavidya@\\textit{adhyātmavidyā}"
    "rajavidya@\\textit{rājavidyā}"
    "rajaguhya@\\textit{rājaguhyam}"
    "karma@\\textit{karma}"
    "ksatradharma@\\textit{kṣatradharma}"
    "Rajayoga@Rājayoga"
    "northern India"
    "Netratantra@\\textit{Netratantra}"
    "kha@\\textit{kha}"
    "Netratantra@\\textit{Netratantra}!kingship"
    "rajapurohita@\\textit{rājapurohita}"
    "Saiva@Śaiva"
    "Mahayana@Mahāyāna"
    "mantra rituals"
    "Sivayogapradipika@\\textit{Śivayogapradīpikā}"
    "Powell, Seth"
    "Sivatattvaratnakara@\\textit{Śivatattvaratnākara}"
    "Basavabhupala, Keladi@Basavabhūpāla, Keḷadi"
    "Basavaraja@Basavarāja"
    "Basavappa Nayaka I@Basavāppa Nāyaka I"
    "Ikkeri"
    "Karnataka"
    "yoga!for kings"
    "Tattvayogabindu@\\textit{Tattvayogabindu}!royal commission"
    "Astangayoga@Aṣṭāṅgayoga"
    "sukumara@\\textit{sukumāra}"
    "pranayama@\\textit{prāṇāyāma}"
    "samadhi@\\textit{samādhi}"
    "kumbhaka@\\textit{kumbhaka}"
    "mudra@\\textit{mudrā}"
    "Hargreaves, Jaqueline"
    "royal yogins"
    "Siva@Śiva"
    "Brahma@Brahmā"
    "Visnu@Viṣṇu"
    "Bhuri Singh Museum"
    "Mandhata@Mandhāta"
    "Nurpur"
    "Pahari region"
    "Cleveland Museum of Art"
    "Wellcome Collection"
    "Patumkar, Appu Sahib"
    "dhanurasana@\\textit{dhanurāsana}"
    "nobility"
    "rajayoga@\\textit{rājayoga}!yoga for kings"
    "manuscript witnesses"
    "final rubrics"
    "Formigatti, Camillo"
    "colophons"
    "source texts"
    "testimonia"
    "textual parallels"
    "stemmatic analysis"
    "critical edition!conventions"))
 :latex)

